### PR TITLE
Add stop() and restart() methods + bug fixes

### PR DESCRIPTION
**Pull request by legauntt**
"idle:stop" event didn't seem to work right - fixed.

Also, added a couple of methods, that were useful, at least for me.

### CODE REVIEW

**Review by gabrielstuff — COMMENTED** [review]
Hey @TheGauntt thanks for the whole work. Could you please elaborate on the document.hidden functionnality you added ?

Thanks !!

g

**Comment by hugohil** [comment]
Hi @TheGauntt !
Any update on @gabrielstuff question ?

Thanks !

**Comment by legauntt** [comment]
Earlier, there was `this.visible = !this.settings.startAtIdle`

But, because the "visibleStateChanged" events are used, this is never fired until you go away and come back, or vice versa. So you may miss an onHide() or onShow() event, the first time

So to me, makes sense to use `document.hidden` for starting visible state

https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden

**Comment by gabrielstuff** [comment]
@hugohil we should talk about that this week. Would be a great improvement to idle-vue.

**Pull request closed without merging**
